server:
  port: 8089
spring:
  application:
    name: lengleng-router-@artifactId@
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
    tencent:
      metadata:
        content:
          version: local
