spring:
  application:
    name: lengleng-circuitbreaker-tencent-circuitbreaker-provider
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
    tencent:
      metadata:
        content:
          version: local
server:
  port: 8012
