server:
  port: 8089
spring:
  application:
    name: lengleng-circuitbreaker-@artifactId@
  cloud:
    polaris:
      address: grpc://183.47.111.80:8091
    loadbalancer:
      configurations: polaris # 2020.0.x SDK需要添加这个配置
